import type {
  EmployeeMaster,
  LeaveBalance,
  LeaveRecord,
  AttendanceRecord,
  AccommodationCase,
  PerformanceReview,
  HRCase,
  CaseNote,
  Training,
  EmployeeTraining,
  Policy,
  UserGroup,
} from "./types";

export const employees: EmployeeMaster[] = [
  {
    id: "emp-1",
    name: "Alex Chen",
    email: "alex.chen@company.com",
    dateOfHire: "2021-03-15",
    team: "Product",
    managerId: "emp-2",
    level: "L4",
    workLocation: "HQ",
    phone: "+1 (415) 555-0123",
    dateOfBirth: "1992-07-22",
    nationality: "United States",
    maritalStatus: "Single",
    emergencyContact: "Jen Chen (sibling)",
    emergencyContactPhone: "+1 (415) 555-0199",
    address: {
      line1: "1248 Market Street",
      line2: "Apt 4B",
      city: "San Francisco",
      state: "CA",
      postalCode: "94102",
      country: "United States",
    },
    teamHistory: [{ from: "2021-03-15", team: "Product", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2021-03-15", plan: "Standard" }],
  },
  {
    id: "emp-2",
    name: "Jordan Lee",
    email: "jordan.lee@company.com",
    dateOfHire: "2019-06-01",
    team: "Product",
    level: "L6",
    workLocation: "HQ",
    phone: "+1 (650) 555-0144",
    dateOfBirth: "1988-03-11",
    nationality: "United States",
    maritalStatus: "Married",
    emergencyContact: "Taylor Lee (spouse)",
    emergencyContactPhone: "+1 (650) 555-0145",
    address: {
      line1: "3200 Alpine Road",
      city: "Portola Valley",
      state: "CA",
      postalCode: "94028",
      country: "United States",
    },
    teamHistory: [{ from: "2019-06-01", team: "Product" }],
    benefitsHistory: [{ effectiveDate: "2019-06-01", plan: "Premium" }],
  },
  {
    id: "emp-3",
    name: "Sam Rivera",
    email: "sam.rivera@company.com",
    dateOfHire: "2022-01-10",
    dateOfTermination: "2025-01-20",
    team: "Engineering",
    managerId: "emp-2",
    level: "L3",
    workLocation: "Remote",
    phone: "+1 (512) 555-0177",
    dateOfBirth: "1995-11-08",
    nationality: "United States",
    maritalStatus: "Single",
    emergencyContact: "Maria Rivera (parent)",
    emergencyContactPhone: "+1 (512) 555-0178",
    address: {
      line1: "8901 South Congress Ave",
      line2: "Unit 220",
      city: "Austin",
      state: "TX",
      postalCode: "78745",
      country: "United States",
    },
    teamHistory: [{ from: "2022-01-10", to: "2025-01-20", team: "Engineering", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2022-01-10", plan: "Standard" }],
  },
  {
    id: "emp-4",
    name: "Morgan Taylor",
    email: "morgan.taylor@company.com",
    dateOfHire: "2020-08-01",
    dateOfTermination: "2024-09-15",
    team: "Engineering",
    managerId: "emp-2",
    level: "L4",
    workLocation: "HQ",
    phone: "+1 (408) 555-0221",
    dateOfBirth: "1990-01-30",
    nationality: "Canada",
    maritalStatus: "Domestic partnership",
    emergencyContact: "Jamie Taylor (partner)",
    emergencyContactPhone: "+1 (408) 555-0222",
    address: {
      line1: "2550 Walsh Avenue",
      city: "Santa Clara",
      state: "CA",
      postalCode: "95051",
      country: "United States",
    },
    teamHistory: [{ from: "2020-08-01", to: "2024-09-15", team: "Engineering", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2020-08-01", plan: "Standard" }],
  },
  {
    id: "emp-5",
    name: "Casey Kim",
    email: "casey.kim@company.com",
    dateOfHire: "2021-11-15",
    dateOfTermination: "2024-06-20",
    team: "Operations",
    level: "L3",
    workLocation: "HQ",
    phone: "+1 (206) 555-0330",
    dateOfBirth: "1993-09-14",
    nationality: "United States",
    maritalStatus: "Single",
    emergencyContact: "Robin Kim (sibling)",
    emergencyContactPhone: "+1 (206) 555-0331",
    address: {
      line1: "410 West Harrison Street",
      city: "Seattle",
      state: "WA",
      postalCode: "98119",
      country: "United States",
    },
    teamHistory: [{ from: "2021-11-15", to: "2024-06-20", team: "Operations" }],
    benefitsHistory: [{ effectiveDate: "2021-11-15", plan: "Standard" }],
  },
  {
    id: "emp-6",
    name: "Riley Johnson",
    email: "riley.johnson@company.com",
    dateOfHire: "2019-04-01",
    dateOfTermination: "2024-03-10",
    team: "Product",
    managerId: "emp-2",
    level: "L5",
    workLocation: "HQ",
    phone: "+1 (617) 555-0440",
    dateOfBirth: "1987-05-03",
    nationality: "United States",
    maritalStatus: "Married",
    emergencyContact: "Quinn Johnson (spouse)",
    emergencyContactPhone: "+1 (617) 555-0441",
    address: {
      line1: "77 Massachusetts Avenue",
      line2: "Apt 12",
      city: "Cambridge",
      state: "MA",
      postalCode: "02139",
      country: "United States",
    },
    teamHistory: [{ from: "2019-04-01", to: "2024-03-10", team: "Product", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2019-04-01", plan: "Premium" }],
  },
  {
    id: "emp-7",
    name: "Jamie Foster",
    email: "jamie.foster@company.com",
    dateOfHire: "2022-09-12",
    team: "Engineering",
    managerId: "emp-2",
    level: "L4",
    workLocation: "Remote",
    phone: "+1 (303) 555-0550",
    dateOfBirth: "1994-02-18",
    nationality: "United States",
    maritalStatus: "Single",
    emergencyContact: "Chris Foster (parent)",
    emergencyContactPhone: "+1 (303) 555-0551",
    address: { line1: "1600 Broadway", city: "Denver", state: "CO", postalCode: "80202", country: "United States" },
    teamHistory: [{ from: "2022-09-12", team: "Engineering", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2022-09-12", plan: "Standard" }],
  },
  {
    id: "emp-8",
    name: "Taylor Nguyen",
    email: "taylor.nguyen@company.com",
    dateOfHire: "2023-02-01",
    team: "Product",
    managerId: "emp-2",
    level: "L3",
    workLocation: "HQ",
    phone: "+1 (415) 555-0660",
    dateOfBirth: "1998-06-22",
    nationality: "United States",
    maritalStatus: "Single",
    emergencyContact: "Minh Nguyen (parent)",
    emergencyContactPhone: "+1 (415) 555-0661",
    address: { line1: "100 Market Street", line2: "Suite 500", city: "San Francisco", state: "CA", postalCode: "94105", country: "United States" },
    teamHistory: [{ from: "2023-02-01", team: "Product", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2023-02-01", plan: "Standard" }],
  },
  {
    id: "emp-9",
    name: "Morgan Hayes",
    email: "morgan.hayes@company.com",
    dateOfHire: "2021-05-17",
    team: "Operations",
    level: "L4",
    workLocation: "HQ",
    phone: "+1 (404) 555-0770",
    dateOfBirth: "1991-11-09",
    nationality: "United States",
    maritalStatus: "Married",
    emergencyContact: "Jordan Hayes (spouse)",
    emergencyContactPhone: "+1 (404) 555-0771",
    address: { line1: "600 Peachtree Street", city: "Atlanta", state: "GA", postalCode: "30308", country: "United States" },
    teamHistory: [{ from: "2021-05-17", team: "Operations" }],
    benefitsHistory: [{ effectiveDate: "2021-05-17", plan: "Standard" }],
  },
  {
    id: "emp-10",
    name: "Reese Cooper",
    email: "reese.cooper@company.com",
    dateOfHire: "2020-11-01",
    team: "Engineering",
    managerId: "emp-2",
    level: "L5",
    workLocation: "Remote",
    phone: "+1 (312) 555-0880",
    dateOfBirth: "1989-08-14",
    nationality: "United States",
    maritalStatus: "Domestic partnership",
    emergencyContact: "Alex Cooper (partner)",
    emergencyContactPhone: "+1 (312) 555-0881",
    address: { line1: "233 South Wacker Drive", city: "Chicago", state: "IL", postalCode: "60606", country: "United States" },
    teamHistory: [{ from: "2020-11-01", team: "Engineering", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2020-11-01", plan: "Premium" }],
  },
  {
    id: "emp-11",
    name: "Quinn Bennett",
    email: "quinn.bennett@company.com",
    dateOfHire: "2023-07-10",
    team: "Product",
    managerId: "emp-2",
    level: "L3",
    workLocation: "Remote",
    phone: "+1 (617) 555-0990",
    dateOfBirth: "1996-04-05",
    nationality: "Canada",
    maritalStatus: "Single",
    emergencyContact: "Sam Bennett (sibling)",
    emergencyContactPhone: "+1 (617) 555-0991",
    address: { line1: "1 Beacon Street", city: "Boston", state: "MA", postalCode: "02108", country: "United States" },
    teamHistory: [{ from: "2023-07-10", team: "Product", managerId: "emp-2" }],
    benefitsHistory: [{ effectiveDate: "2023-07-10", plan: "Standard" }],
  },
];

export const leaveBalances: Record<string, LeaveBalance[]> = {
  "emp-1": [
    { employeeId: "emp-1", type: "sick", balance: 40, unit: "hours", accrued: 48, used: 8 },
    { employeeId: "emp-1", type: "paid", balance: 80, unit: "hours", accrued: 96, used: 16 },
    { employeeId: "emp-1", type: "floating", balance: 16, unit: "hours", accrued: 16, used: 0 },
  ],
  "emp-2": [
    { employeeId: "emp-2", type: "sick", balance: 4, unit: "hours", accrued: 56, used: 52 },
    { employeeId: "emp-2", type: "paid", balance: 8, unit: "hours", accrued: 120, used: 112 },
  ],
  "emp-4": [
    { employeeId: "emp-4", type: "sick", balance: 24, unit: "hours", accrued: 48, used: 24 },
    { employeeId: "emp-4", type: "paid", balance: 40, unit: "hours", accrued: 96, used: 56 },
  ],
  "emp-5": [
    { employeeId: "emp-5", type: "sick", balance: 32, unit: "hours", accrued: 48, used: 16 },
    { employeeId: "emp-5", type: "paid", balance: 64, unit: "hours", accrued: 96, used: 32 },
  ],
  "emp-6": [
    { employeeId: "emp-6", type: "sick", balance: 48, unit: "hours", accrued: 56, used: 8 },
    { employeeId: "emp-6", type: "paid", balance: 80, unit: "hours", accrued: 120, used: 40 },
  ],
  "emp-7": [
    { employeeId: "emp-7", type: "sick", balance: 32, unit: "hours", accrued: 40, used: 8 },
    { employeeId: "emp-7", type: "paid", balance: 72, unit: "hours", accrued: 96, used: 24 },
  ],
  "emp-8": [
    { employeeId: "emp-8", type: "sick", balance: 40, unit: "hours", accrued: 40, used: 0 },
    { employeeId: "emp-8", type: "paid", balance: 88, unit: "hours", accrued: 96, used: 8 },
  ],
  "emp-9": [
    { employeeId: "emp-9", type: "sick", balance: 48, unit: "hours", accrued: 56, used: 8 },
    { employeeId: "emp-9", type: "paid", balance: 96, unit: "hours", accrued: 120, used: 24 },
  ],
  "emp-10": [
    { employeeId: "emp-10", type: "sick", balance: 56, unit: "hours", accrued: 56, used: 0 },
    { employeeId: "emp-10", type: "paid", balance: 120, unit: "hours", accrued: 120, used: 0 },
  ],
  "emp-11": [
    { employeeId: "emp-11", type: "sick", balance: 24, unit: "hours", accrued: 32, used: 8 },
    { employeeId: "emp-11", type: "paid", balance: 64, unit: "hours", accrued: 80, used: 16 },
  ],
};

export const leaveRecords: LeaveRecord[] = [
  {
    id: "lv-1",
    employeeId: "emp-1",
    type: "paid",
    startDate: "2025-02-10",
    endDate: "2025-02-12",
    status: "approved",
    requestedAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "lv-2",
    employeeId: "emp-1",
    type: "sick",
    startDate: "2025-02-25",
    endDate: "2025-02-25",
    status: "pending",
    requestedAt: "2025-02-24T09:00:00Z",
  },
];

export const attendanceToday: AttendanceRecord[] = [
  { employeeId: "emp-1", date: "2025-02-28", checkIn: "09:00", checkOut: "18:00", status: "present" },
  { employeeId: "emp-2", date: "2025-02-28", checkIn: "08:30", status: "present" },
];

export const accommodationCases: AccommodationCase[] = [
  {
    id: "acc-1",
    employeeId: "emp-1",
    type: "work_from_home",
    status: "approved",
    submittedAt: "2024-11-01T00:00:00Z",
    decidedAt: "2024-11-15T00:00:00Z",
    caseManagerId: "hr-1",
    hasAttachments: false,
  },
];

export const performanceReviews: PerformanceReview[] = [
  {
    id: "perf-1",
    employeeId: "emp-1",
    cycle: "2024",
    selfInput: "Strong delivery on Q3 roadmap.",
    managerRating: 4,
    finalDecision: "Exceeds",
    compensationChange: "5% merit",
  },
  {
    id: "perf-2-recent",
    employeeId: "emp-2",
    cycle: "2025-Q1",
    selfInput: "Focused on roadmap delivery; some quality issues acknowledged.",
    managerRating: 2,
    finalDecision: "Does not meet",
    compensationChange: "0%",
  },
  {
    id: "perf-4",
    employeeId: "emp-4",
    cycle: "2023",
    managerRating: 3,
    finalDecision: "Meets",
    compensationChange: "3% merit",
  },
  {
    id: "perf-5",
    employeeId: "emp-5",
    cycle: "2023",
    managerRating: 2,
    finalDecision: "Needs Improvement",
    compensationChange: "0%",
  },
  {
    id: "perf-6",
    employeeId: "emp-6",
    cycle: "2023",
    managerRating: 4,
    finalDecision: "Exceeds",
    compensationChange: "5% merit",
  },
];

export const hrCases: HRCase[] = [
  {
    id: "case-1",
    employeeId: "emp-1",
    type: "query",
    subject: "Leave policy for parental leave",
    status: "open",
    createdAt: "2025-02-20T14:00:00Z",
    assignedTo: "hr-1",
  },
  {
    id: "case-2",
    employeeId: "emp-3",
    type: "investigation",
    subject: "Exit process",
    status: "resolved",
    createdAt: "2025-01-18T00:00:00Z",
    assignedTo: "hr-1",
  },
  // Ongoing investigation for Jordan Lee: quality of work and delivery concerns
  {
    id: "case-inv-2",
    employeeId: "emp-2",
    type: "investigation",
    subject: "Performance and quality of work concerns – missed deadlines and quality bar",
    status: "in_progress",
    createdAt: "2025-01-15T10:00:00Z",
    assignedTo: "hr-1",
    incidentDate: "2025-01-10",
    initialFinding:
      "Manager escalation: repeated missed quality bar on deliverables, two critical deadlines missed in Q4. Formal check-in and PIP under consideration.",
    caseNotes: [
      {
        id: "nj1",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "interview",
        content: "Manager reported employee has not met quality of work bar in last two review cycles; feedback provided in 1:1s and in 2025-Q1 review.",
        createdAt: "2025-01-20T14:00:00Z",
      },
    ],
  },
  // Present investigation: colleague complaint - photos in restricted area
  {
    id: "case-inv-1",
    employeeId: "emp-1",
    type: "investigation",
    subject: "Alleged policy violation: taking pictures in confidential restricted office space",
    status: "in_progress",
    createdAt: "2025-02-15T09:00:00Z",
    assignedTo: "hr-1",
    incidentDate: "2025-02-14",
    initialFinding:
      "Employee was seen using phone in restricted area. Security footage confirms device usage. Colleague reported employee may have been taking photos of confidential materials.",
    caseNotes: [
      {
        id: "n1",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "interview",
        content:
          "Interviewed 3 colleagues present in area. Two confirmed seeing employee with phone out. One stated employee appeared to be taking photos of whiteboard.",
        createdAt: "2025-02-16T10:00:00Z",
      },
      {
        id: "n2",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "evidence",
        content:
          "Security footage obtained from Security team. Footage shows employee holding phone in horizontal orientation (camera mode) pointed at whiteboard in restricted zone B-204. Timestamp: 2025-02-14 14:32.",
        createdAt: "2025-02-17T11:00:00Z",
      },
      {
        id: "n3",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "discussion",
        content:
          "Discussion with employee (Alex Chen). Employee acknowledged having phone in restricted area but stated they were checking messages, not taking photos. Employee expressed regret and stated they were unaware of strict no-device policy in that zone.",
        createdAt: "2025-02-18T14:00:00Z",
      },
      {
        id: "n4",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "finding",
        content:
          "Initial finding: Employee was seen using phone in restricted area. Security footage supports device usage. Employee's explanation (checking messages) conflicts with witness account of photo-taking. Policy clearly states no personal devices in restricted zones. Awaiting termination review decision.",
        createdAt: "2025-02-20T09:00:00Z",
      },
    ],
  },
  // Termination review case (initiated from case-inv-1) - HR must review snapshot + AI before submitting
  {
    id: "case-term-review-1",
    employeeId: "emp-1",
    type: "termination",
    subject: "Termination review: Policy violation - device/photography in restricted area",
    status: "in_progress",
    createdAt: "2025-02-21T10:00:00Z",
    assignedTo: "hr-1",
    parentCaseId: "case-inv-1",
    incidentDate: "2025-02-14",
    initialFinding:
      "Employee was seen using phone in restricted area. Security footage confirms device usage. Colleague reported employee may have been taking photos of confidential materials.",
    caseNotes: [], // inherits context from parent; HR adds notes when submitting
  },
  // Past termination cases (for RAG) - same reason: photos/device in restricted area
  {
    id: "case-term-past-1",
    employeeId: "emp-4",
    type: "termination",
    subject: "Termination: Unauthorized photography in restricted area",
    status: "resolved",
    createdAt: "2024-09-01T00:00:00Z",
    assignedTo: "hr-1",
    incidentDate: "2024-08-28",
    initialFinding: "Employee photographed confidential documents in restricted zone.",
    terminationReason: "Severe policy violation - photography of confidential materials in restricted area. Zero tolerance.",
    rehireEligible: false,
    appliedPolicyClauseId: "restricted-area-photography",
    caseNotes: [
      {
        id: "pn1",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "finding",
        content: "Security footage confirmed photography. Documents were classified. Immediate termination recommended.",
        createdAt: "2024-08-30T00:00:00Z",
      },
    ],
  },
  {
    id: "case-term-past-2",
    employeeId: "emp-5",
    type: "termination",
    subject: "Termination: Phone usage and suspected photography in restricted zone",
    status: "resolved",
    createdAt: "2024-06-05T00:00:00Z",
    assignedTo: "hr-1",
    incidentDate: "2024-06-03",
    initialFinding: "Employee seen with phone in restricted area. Witness reported possible photo-taking.",
    terminationReason: "Policy violation - device in restricted zone. Prior written warning on same policy. Escalation to termination.",
    rehireEligible: true,
    appliedPolicyClauseId: "restricted-area-second-offense",
    caseNotes: [
      {
        id: "pn2",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "finding",
        content: "Second offense. First warning issued 3 months prior for same policy. Termination approved.",
        createdAt: "2024-06-04T00:00:00Z",
      },
    ],
  },
  {
    id: "case-term-past-3",
    employeeId: "emp-6",
    type: "termination",
    subject: "Termination: Unauthorized device in restricted area - photo evidence",
    status: "resolved",
    createdAt: "2024-03-01T00:00:00Z",
    assignedTo: "hr-1",
    incidentDate: "2024-02-28",
    initialFinding: "Employee used phone to photograph whiteboard in restricted meeting room.",
    terminationReason: "Severe breach - photography of proprietary information. No prior violations but severity warrants termination.",
    rehireEligible: false,
    appliedPolicyClauseId: "restricted-area-photography",
    caseNotes: [
      {
        id: "pn3",
        authorId: "hr-1",
        authorName: "HR Team",
        type: "finding",
        content: "Clear evidence from security. Employee admitted to taking photo. Confidential content on whiteboard.",
        createdAt: "2024-02-29T00:00:00Z",
      },
    ],
  },
];

export const trainings: Training[] = [
  { id: "tr-1", name: "Data Security Essentials", type: "mandatory", category: "compliance", dueDate: "2025-03-31" },
  { id: "tr-2", name: "Product Management Career Track", type: "optional", category: "career" },
];

export const employeeTrainings: EmployeeTraining[] = [
  { employeeId: "emp-1", trainingId: "tr-1", status: "completed", completedAt: "2025-01-15" },
  { employeeId: "emp-1", trainingId: "tr-2", status: "in_progress" },
  { employeeId: "emp-4", trainingId: "tr-1", status: "completed", completedAt: "2023-06-01" },
  { employeeId: "emp-5", trainingId: "tr-1", status: "completed", completedAt: "2022-03-15" },
  { employeeId: "emp-6", trainingId: "tr-1", status: "completed", completedAt: "2020-05-01" },
  { employeeId: "emp-7", trainingId: "tr-1", status: "completed", completedAt: "2024-06-01" },
  { employeeId: "emp-8", trainingId: "tr-1", status: "in_progress" },
  { employeeId: "emp-10", trainingId: "tr-1", status: "completed", completedAt: "2023-01-10" },
];

export const policies: Policy[] = [
  {
    id: "pol-1",
    name: "Leave Accrual Policy",
    version: "2.1",
    effectiveDate: "2024-01-01",
    body: "Full-time employees accrue 8 hours sick and 8 hours paid leave per 15 days. Floating holidays: 2 per year.",
    category: "leave",
  },
  {
    id: "pol-2",
    name: "Performance Review Process",
    version: "1.0",
    effectiveDate: "2024-01-01",
    body: "Annual review cycle. Self-input, manager rating, calibration, final decision and compensation.",
    category: "performance",
  },
  {
    id: "pol-termination",
    name: "Employee Termination Policy",
    version: "1.0",
    effectiveDate: "2024-01-01",
    body: `EMPLOYEE TERMINATION POLICY

1. GROUNDS FOR TERMINATION
Termination may result from: performance issues, policy violations, misconduct, or redundancy.

2. RESTRICTED AREA & CONFIDENTIALITY VIOLATIONS
- No personal devices (phones, cameras, smartwatches) permitted in designated restricted zones (e.g., B-200 series, confidential meeting rooms).
- Photography, recording, or transmission of confidential/proprietary information is strictly prohibited.
- Violations are categorized by severity:
  - First offense (minor): Written warning, mandatory retraining.
  - First offense (severe): Termination. Severe = photography of documents/screens, intentional breach.
  - Second offense (any): Termination. Prior warning on same policy escalates to termination.
- Rehire eligibility: Severe breaches (photography of confidential materials) = not eligible for rehire. Lesser violations may be eligible after 12 months.

3. TERMINATION REVIEW PROCESS
Before submitting formal termination, HR must:
- Review employee data snapshot (performance, attendance, prior cases, training compliance).
- Consider manager and stakeholder feedback.
- Document evidence and policy alignment.
- Submit termination with stated reason and rehire consequence.`,
    category: "termination",
  },
];

export const userGroups: UserGroup[] = [
  {
    id: "grp-managers",
    name: "Managers",
    permissions: [
      { system: "performance", operation: "read" },
      { system: "employee_master", operation: "read", attributeScope: "basic" },
    ],
  },
  {
    id: "grp-hr",
    name: "HR",
    permissions: [
      { system: "employee_master", operation: "read" },
      { system: "leave", operation: "read" },
      { system: "accommodations", operation: "read", attributeScope: "no_medical" },
      { system: "cases", operation: "read" },
      { system: "cases", operation: "write" },
      { system: "performance", operation: "read" },
      { system: "policy", operation: "read" },
    ],
  },
  {
    id: "grp-case-managers",
    name: "Disability & Accommodation Case Managers",
    permissions: [
      { system: "accommodations", operation: "read" },
      { system: "accommodations", operation: "write" },
      { system: "accommodations", operation: "delete" },
    ],
  },
  {
    id: "grp-admin",
    name: "Admin",
    permissions: [
      { system: "employee_master", operation: "read" },
      { system: "employee_master", operation: "write" },
      { system: "leave", operation: "read" },
      { system: "leave", operation: "write" },
      { system: "accommodations", operation: "read" },
      { system: "accommodations", operation: "write" },
      { system: "performance", operation: "read" },
      { system: "cases", operation: "read" },
      { system: "cases", operation: "write" },
      { system: "training", operation: "read" },
      { system: "training", operation: "write" },
      { system: "policy", operation: "read" },
      { system: "policy", operation: "write" },
    ],
  },
];

// Mock session: current user (simulate SSO)
export const currentUser = {
  id: "user-1",
  email: "jordan.lee@company.com",
  name: "Jordan Lee",
  employeeId: "emp-2",
  roles: ["manager", "hr"] as const,
  groupIds: ["grp-managers", "grp-hr"],
};
